name = "simulations"
uuid = "cecdf99a-6d3d-4193-a10b-41362f56cb7a"
authors = ["danielemiche <74101475+danielemiche@users.noreply.github.com>"]
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
